### ISSUE TITLE
test rendering with Xpra

### ISSUE THREAD

**Issue by porst17** [malex984/dockapp#11]
Hopefully, http://xpra.org solves the per-host-customization issues related to GPU drivers.

Links:
- https://www.xpra.org/trac/wiki/Usage/Docker
- https://github.com/rogaha/docker-desktop

Known issues:
- VirtualBox GPU driver is blacklisted for client -> always falls back to Mesa software rendering

**Comment by porst17** [comment]
Hmmm ... I dug a little bit deeper into the docs of Xpra and it looks like I was wrong. OpenGL rendering is done on the server side as it seems (but maybe you can check this?). At least I couldn't get it to work. It was always using Mesa software rendering for `glxgears`. Maybe I am missing something but maybe I was just plain wrong.

**Comment by malex984** [comment]
hmm, i also failed to get proper OpenGL performance (same system, no containers, unix shared sockets (AFAIK), xpra acting as screen): https://github.com/malex984/dockapp/wiki/Xpra

**Comment by malex984** [comment]
=> does not look suitable for our usage yet :(
