### ISSUE TITLE
Protection needed to arbitrate station requests and server requests

### ISSUE THREAD

**Issue by elondaits** [malex984/dockapp#27]
If a station starts on its own it'll try to start an application. If a server starts the station it'll also try to start an application. Some arbitration is needed so both things don't conflict.

e.g. An explicit API running in the station for switching apps which has some sort of locking or IPC mechanism (lock or queue). Requests from the server fail if there's a local app switch.

**Comment by malex984** [comment]
It has to be part of Hilbert-CLI-Server / Hilbert-CLI-Station design: hilbert/hilbert-docker-images#28

**Comment by malex984** [comment]
Currently Hilbert client-side bash script (`hilbert-station`) uses a lockfile to prevent two actions running in the same time. In case of a lock script execution will fail with an error code 2 (see `start_locking` in `tools/hilbert-station`)
