### ISSUE TITLE
Setup minimal Vagrant box

### ISSUE THREAD

**Issue by porst17** [malex984/dockapp#3]
This should be a vagrant box with GUI (default is cli). `boot2docker` is a VM solution anyway, so way not just use a VM with GUI and docker installed instead of forwarding e.g. X11? This will probably also make things like sound easier. Network printers will also work.
- decide about base distro (I am happy with Ubuntu, but maybe some other distro has better VirtualBox integration which I think is most important for this box)
- it would be nice to use an approach similar to the `Dockerfile` via provisioning (Ansible or similar http://docs.vagrantup.com/v2/provisioning/ansible.html).
- don't forget to install Virtual Box guest additions, if this is not part of the base image anyway
- should we have two separate boxes? one development/packaging/testing containers and one for demonstration purposes, i.e. `vagrant init repo/demoimage:version && vagrant up` (just copied a few lines from the vagrant tutorial, might be plain wrong) fires up the demo prototype instantly (probably the dev image is the demo image plus dev tools)

Anything else?

**Comment by malex984** [comment]
i agree, but note that `boot2docker` is very neat and can enable one to develop/test dockapp from any machine / OS...

**Comment by porst17** [comment]
Well, this is partially true because there exist X11 server implementations on most systems. But audio is a different story as well as all other hardware that's not accessible via network. With a regular VM, you can even connect exotic hardware to the VM host and forward it to the docker host which allows to use it in the containers. In our case, such devices will most likely be input devices like _Space Navigator_ or _Leap Motion_.

I also would like to maintain only a single platform. If we want to support `boot2docker` on MS Windows, we also cannot simply use `bash` scripts anymore on the host unless you install `bash` separately. In addition, all manuals have to be written with different platforms in mind. Also an issue of human resources ...

My current setup is as follows: I have a VirtualBox VM running Ubuntu 14.04 on my Mac. I can share folders and devices with the VM from the host which in turn can be access by dockers `--dev`, `--privileged` and `--volume` options inside containers. I think that's way more fail proof than using `boot2docker` for our purpose.

We can also make the `vagrant` dev image public. This can be used by everybody for development in a (more or less) clearly defined environment.

**Comment by malex984** [comment]
IMO the current vagrant box is pretty ok for a 1st demo. I am trying to minimize the whole thing but it involves rather a lot of experimentation, which is why the progress is soooooo slow :(

**Comment by porst17** [comment]
I agree. We will keep it like it is until there is real demand for further optimization.
