### ISSUE TITLE
Update DockerHub automatic building

### ISSUE THREAD

**Issue by malex984** [malex984/dockapp#31]
Update due to new github repository URL

TODO: do we need `-devel` versions of images? Currently only `master` branch triggers image building

**Comment by elondaits** [comment]
Once the images are running at a customer you might want to develop and test changes (i.e. run devel images in a test server) before merging to master.

**Comment by malex984** [comment]
Docker Hub Registry seems to require organization access.

See also https://docs.docker.com/docker-hub/builds/ for details

**Comment by malex984** [comment]
It is working again upon changes to `devel` branch
