### ISSUE TITLE
Separate shared helper scripts into a separate sub-folder

### ISSUE THREAD

**Issue by malex984** [malex984/dockapp#37]
E.g. upgrade.sh/update.sh/install/clean.sh, setup_ogl, launcher.sh etc

**Comment by malex984** [comment]
@porst17 No, those scripts belong to directories of corresponding images (e.g. `hilbert/base`, `hilbert/gui`) due to restrictions of `docker build`. 
IMO this can be closed.

**Comment by porst17** [comment]
The [`Dockerfile`](https://github.com/hilbert/hilbert-docker-images/blob/a20fe0962d6be662a71012e454c7846549d583a7/images/base/Dockerfile#L6) now includes these scripts via `COPY update.sh install.sh upgrade.sh clean.sh /usr/local/bin/`, i.e. they will be reused in derived images. This satisfies _sharing_ for me.
