### ISSUE TITLE
Upload docker images to public and private docker registries

### ISSUE THREAD

**Issue by porst17** [malex984/dockapp#7]
I suggest the following separation:
* all infrastructure related containers should go into public repositories
* all free app containers should go in public repositories
* all apps intended to be used in a commercial environment go into a private repository

Be aware of license restrictions that may arise when proprietary libraries (e.g. Oracle Java) or drivers (e.g. NVidia display driver) are installed inside a container. I am not saying that it is not allows to build and upload such containers but one has to check the restriction for each individual proprietary package.

**Comment by malex984** [comment]
@porst17  it is currently done that way AFAIK
