### ISSUE TITLE
Configutation management

### ISSUE THREAD

**Issue by porst17** [malex984/dockapp#8]
How can we realize the configuration of the host and the individual apps?

**Comment by malex984** [comment]
What do you think about the latest addition to dockapp: setting-management? 
Does it pass for a Configutation management? 

One thing that is still remains to be done is storing/restoring settings into/from a file...  i will probably generate a bash script to be sourced by bash (and regenerated laster on).

**Comment by porst17** [comment]
I think the current implementation suffices for now.
